#
# Copyright (C) 2022 Ing <https://github.com/Gentleelephant>
name: Apply for mailbox
on:
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ADMIN: ${{ secrets.KUBESPHERE_ADMIN }}
    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@main

      - name: Init Env
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install yagmail

      - name: Get Issues Info
        if: github.event_name == 'issues'
        id: get-issues
        uses: actions/github-script@v6
        with:
          script: |  
            function randomPassword(length) {
                length = Number(length);
                if (length < 6) {
                  length = 6;
                } else if (length > 16) {
                  length = 16;
                }
                let passwordArray = ['ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz', '1234567890'];
                var password = [];
                let n = 0;
                for (let i = 0; i < length; i++) {
                    if ( password.length < (length - 4) ) {
                      let arrayRandom = Math.floor(Math.random() * 4);
                      let passwordItem = passwordArray[arrayRandom];
                      let item = passwordItem[Math.floor(Math.random() * passwordItem.length)];
                      password.push(item);
                    } else {
                      let newItem = passwordArray[n];
                      let lastItem = newItem[Math.floor(Math.random() * newItem.length)];
                      let spliceIndex = Math.floor(Math.random() * password.length);
                      password.splice(spliceIndex, 0, lastItem);
                      n++
                    }
                }
                return password.join("");
            }
            var passwd = randomPassword(12);
            var issuenumber = ${{ toJSON(github.event.issue.number) }};
            var issueauth = ${{ toJSON(github.event.issue.user.login) }};
            var issuetitle = ${{ toJSON(github.event.issue.title) }};
            var issuebody = ${{ toJSON(github.event.issue.body) }};
            var splits = issuetitle.split(' ');
            core.setOutput("issuenumber", JSON.stringify(issuenumber));
            core.setOutput("issueauth", JSON.stringify(issueauth));
            core.setOutput("issuebody", JSON.stringify(issuebody));
            core.setOutput("prefix", JSON.stringify(splits[0]))
            core.setOutput("mail", JSON.stringify(splits[1]));
            core.setOutput("reply", JSON.stringify(issuebody));
            core.setOutput("passwd", JSON.stringify(passwd));
      - name: Set Issues Info
        if: github.event_name == 'issues' && success()
        run: |
#          echo issuenumber: ${{ steps.get-issues.outputs.issuenumber }}
#          echo issueauth:   ${{ steps.get-issues.outputs.issueauth }}
#          echo mail: ${{ steps.get-issues.outputs.mail }}
#          echo passwd: ${{ steps.get-issues.outputs.passwd }}
#          echo issuebody:   ${{ steps.get-issues.outputs.issuebody }}
          echo env-issuenumber=${{ steps.get-issues.outputs.issuenumber }} >> $GITHUB_ENV
          echo env-issueauth=${{ steps.get-issues.outputs.issueauth }} >> $GITHUB_ENV
          echo env-issuetitle=${{ steps.get-issues.outputs.issuetitle }} >> $GITHUB_ENV
          echo env-issuebody=${{ steps.get-issues.outputs.issuebody }} >> $GITHUB_ENV
          echo env-prefix=${{ steps.get-issues.outputs.prefix }} >> $GITHUB_ENV
          echo env-mail=${{ steps.get-issues.outputs.mail }} >> $GITHUB_ENV
          echo env-passwd=${{ steps.get-issues.outputs.passwd }} >> $GITHUB_ENV
          echo env-reply=${{ steps.get-issues.outputs.reply }} >> $GITHUB_ENV
      - name: Apply mailbox
        shell: sh
        if: env.env-mail != '' && env.env-prefix == '邮箱申请'  && success()
        run: |
          curl --user zheng1@kubesphere.io:$ADMIN -X POST -d "email=${{ env.env-mail }}" -d "password=${{ env.env-passwd }}" https://mail.kubesphere.io/admin/mail/users/add
      - name: Reply mail
        uses: jannekem/run-python-script-action@v1.2
        id: info
        with:
          script: |
            # This is a sample Python script.
            import yagmail
            # 根据申请邮箱参数和回复邮箱参数，申请邮箱并回复
            def applyMethod():
                # 发件人
                username = '1132960613@qq.com'
                # 授权码密码
                password = 'nswibrevfyznifef'
                # 创建yagmail服务,需要加上服务器地址
                server = yagmail.SMTP(username, password, host='smtp.qq.com')
                # 收件人
                receivers = '1665400978@qq.com'
                text = '您申请的邮箱是: {{ env.env-mail }}\n默认密码是: {{ env.env-passwd }}'  # 报告内容
                title = '邮箱申请回复'  # 邮件标题
                server.send(contents=text, to=receivers, subject=title)
            if __name__ == '__main__':
                applyMethod()
      - name: Create comment
        if: github.event_name == 'issues'  && env.env-prefix == '邮箱申请'  && env.env-mail != '' && success()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
                申请成功
                请访问 https://mail.kubesphere.io/mail/ 尽快修改密码
            `
            })
      - name: Close issue
        if:  env.env-mail != '' && env.env-prefix == '邮箱申请'  && success()
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ env.env-issuenumber }}
          close-reason: completed